import { constants } from "./constants"
import { images } from "./images"
import { anim } from "./anim"
import { accents } from "./accents"

export const R = {
  constants,
  images,
  anim,
  accents,
  faqQuestions: [
    ["Why Should I Choose WolfieSolutions' Help?", "WolfieSolutions is one such website that has 2500+ experts having in-depth knowledge and years of experience. We guarantee every student to provide with high-quality assignments. We provide a number of exclusive features that allow a student to have complete solution to all their writing issues. We have been trusted by millions of students with their assignment writing work throughout the world. You should choose us because we provide you with what you exactly need."],
    ["What Services Do You Provide Other Than Assignment Writing?", "At WolfieSolutions, you will get a wide variety of services, such as assignment writing, essay writing, dissertation writing, thesis writing, homework writing, coursework writing, resume writing, PPT making, poster making, online exam help, and many others. You can check out our 'Services' section to get an insight of everything that we offer to students."],
    ["Is It Ethical to Hire Assignment Writing Services?", "Our assignment writing help is completely ethical as the papers that we offer are meant for reference purpose only. We do not recommend you to submit them as they are to your professor. We provide assignments to students so that they can get an insight into the topic and get ideas to prepare their own assignment. This is completely legal. For better understanding of the usage of assignment, you can refer to our 'Usage Policy.'"],
    ["Do You Provide Revisions? What Are the Charges?", "Yes, we provide unlimited revisions to every customer if they feel dissatisfied with the work. We do not take even a single penny for making the changes. So, if you find some loopholes in the assignments or feel that we have missed something, then you can tell our customer care executives. Our experts will work on the suggested changes and deliver the assignment as soon as they can. However, you can't change assignment requirements at the time of revisions. If you wish to do so, then you will have to pay additional nominal fee."],
    ["How Do You Accept Payments? What Currencies Do You Accept?", "We take payment through Paypal which is a highly secure payment channel and provides security to customers as well as merchants. To open an account, you can reach to paypal.com and register yourself by providing your bank or card details. We prefer GBP from UK and USD from the rest of the countries. However, we also take payment in AUD, SGD, and NZD."],
    ["Can I Contact the Writer Working on My Assignment?", "To make sure the maintenance of standard conversation, we don’t allow our customers to directly contact our writers. Our customer care experts acts as a bridge between you and our writers so you can convey all your messages to them which will be further forwarded to the concerning experts. However, if you share your queries through mail, then our experts will see it directly."],

    ["How Much Time Do You Take to Finish an Assignment?", "It depends on the requirements of the assignment that you have shared with us. Our professionals work day and night tirelessly so that you can submit your assignment on time. If you have urgent delivery request, then our professionals will provide you the assignments within 24 hours. We have a special team of writers who are well-trained to meet urgent deadlines. The prices for urgent orders are slightly high as our experts write high-quality assignment in a very short time. We will suggest you to give us advanced delivery so that we can send the work to you before the deadline and you get sufficient time to go through it."],
    ["How Can I Be Assured That the Assignment Is Not Plagiarized?", "Our highly qualified and competent professionals possess years of experience in academic writing industry and have in-depth knowledge of their respective areas. Every assignment they work on is drafted from the ground up and nothing is copied. The facts and ideas of other authors that we include in the document are cited properly. Moreover, we provide a Turnitin report along with all the orders which ensures that the work is completely authentic and all the sources from where the information is taken are cited. The best part is that this report is provided for free."],
    ["What Are the Different Assignment Standards That You Provide?", "We offer three different assignment standards to students which are- First Class, 2:1, and 2:2. At the time of placing an order, you can mention in the form about the standard in which you want the assignment. The quality provided in all the standards is excellent; however, it slightly varies depending on a few factors, such as price, deadline, and the skill of experts who are working on it."],
    ["What If I Fail My Assignment? Will I Get My Money Back?", "Our professionals work with all their might to provide high-quality assignments that can get our clients excellent grades. However, if due to some reasons you get bad grades or fail the assignment, then you will get the money back to your account within 5-6 working days. However, make sure that the claim you are making for the refund is on justifiable grounds. We do not provide any refund if the assignment fails to bear its purpose due to your personal reasons."],
    ["How Much Do You Charge for Assignment? Can I Pay in Installments?", "The price of every assignment varies as per several factors, such as word count, deadline, topic, referencing style, formatting style, etc. When you fill the order form and submit all your requirements to us, we provide you a final price of the assignment which includes all the taxes. Our pricing structure is transparent and we don't have any hidden charges. We allow our customers to make payment in installments. We charge 50% rate of the assignment before starting the work. You can pay the remaining 50% amount at the time of delivery."],
    ["Do You Resell Your Assignments to Other Customers?", "No, we strictly refrain from doing any such thing. All the papers that we write are unique and meant for a single user only. So, you can be assured that your assignment will not be delivered to any other customer in any circumstances. To assure the same, we provide ownership guarantee to the customers."]
  ]
}