# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy WolfieS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: wolfies
        path: target
  
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: wolfies
    - name: Connect using SSH and clear existing theme folder
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PK }}
        script: |
          rm -rf domains/wolfiesolutions.com/public_html/wp-content/themes/wolfies/*
#     - name: Debug
#       run: ls -al
    - name: Copy new release to theme folder
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PK }}
        source: "./*"
        target: "domains/wolfiesolutions.com/public_html/wp-content/themes/wolfies/"
